require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.1.0_@capacitor+core@4.1.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.1.0_@capacitor+core@4.1.0/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@4.0.1_@capacitor+core@4.1.0/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/.pnpm/@capacitor+camera@4.1.1_@capacitor+core@4.1.0/node_modules/@capacitor/camera'
  pod 'CapacitorGeolocation', :path => '../../node_modules/.pnpm/@capacitor+geolocation@4.0.1_@capacitor+core@4.1.0/node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@4.0.1_@capacitor+core@4.1.0/node_modules/@capacitor/haptics'
  pod 'CapacitorPreferences', :path => '../../node_modules/.pnpm/@capacitor+preferences@4.0.1_@capacitor+core@4.1.0/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.pnpm/@capacitor+push-notifications@4.1.0_@capacitor+core@4.1.0/node_modules/@capacitor/push-notifications'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
